Feature/US-66
alkemyTech/OT279-server pull request #72
Opened 2022-08-31 22:27 UTC by agusflores

Caso 1 (Envio la imagen en base 64, y compruebo que se cargue en la url luego de ser decodeada): 

![image](https://user-images.githubusercontent.com/88952763/187794997-297e7cf7-17f1-4ba1-9d29-73afad51f77b.png)

Caso 2 (Envio por body un organizationId incorrecto): 

![image](https://user-images.githubusercontent.com/88952763/187795868-b0bd5982-a87c-4ff7-9471-a10ad37252b0.png)

Adjunto la imagen de esta forma para demostrar que funciona, ya que en el controller estoy devolviendo un NoContent().

2022-09-01 12:21 UTC, emmanuelranone requested changes
Después cuando el otro controller esté funcionando, mandame de nuevo las capturas completas, donde se evidencie que tu método funcione bien. Por otoro lado te consulto por que tuviste que tocas cosas relacionadas al servicio de aws?

2022-09-02 14:21 UTC, agusflores commented
Lo tuve que adaptar para que cumpla el funcionamiento tanto si le paso un IFormFile o un stream ya que la imagen la recibo en base 64 y tengo que pasarla a stream.

2022-09-02 17:33 UTC, agusflores commented
Caso 1: Se envia una imagen en base 64 y un ID de organizacion existente: 

![image](https://user-images.githubusercontent.com/88952763/188206174-f766b5e4-c91e-429f-90ca-d3da9a26d97e.png)

Caso 2: Se envia una imagen en base 64 y un ID de organizacion inexistente: 

![image](https://user-images.githubusercontent.com/88952763/188206365-8db296ce-a918-4978-8ff0-6d07ee71ea8d.png)

Caso 3: Se envia una imagen en base 64 y no se pasa ninguna 'Order' por lo tanto deberia tomar el valor del campo 'Order' de la ultima Slide: 

![image](https://user-images.githubusercontent.com/88952763/188207373-1dc06fb6-5679-47b7-a26f-bd7fd8cb7713.png)

![image](https://user-images.githubusercontent.com/88952763/188207404-0769d626-1542-4377-911f-e901d6d95d55.png)

2022-09-02 23:35 UTC, emmanuelranone approved these changes

2022-09-02 23:35 UTC, merged