Features/US-92
alkemyTech/OT279-server pull request #81
Opened 2022-09-02 17:59 UTC by javier1616

Added Comments Logical Delete
Some Fix errors
Added Comments Initial Data Seed

Evidence (Added Comments Logical Delete):

![image](https://user-images.githubusercontent.com/90156853/188210936-e1316412-2d51-43c1-88f4-9f50096a7b6b.png)

![image](https://user-images.githubusercontent.com/90156853/188210747-aab840bd-5faa-4f3f-8619-88acd502b92b.png)

![image](https://user-images.githubusercontent.com/90156853/188211273-5154b524-0723-4fbb-987a-128463e3943b.png)

![image](https://user-images.githubusercontent.com/90156853/188211415-fc3392a3-0fa6-4732-8fb3-d14a0740e515.png)

![image](https://user-images.githubusercontent.com/90156853/188211535-5874687c-709d-4bd8-9220-20d35c5ce649.png)

2022-09-02 23:39 UTC, emmanuelranone requested changes
El id lo sacas del token y con eso comparas con la bd, fijate lo que te comenté en slack.
Ademas fijate que me estas pasando otras clases que no tienen que ver con tu historia

2022-09-03 18:44 UTC, javier1616 commented
Cambio de obtencion de datos mediante token enviado en body

2022-09-03 18:45 UTC, javier1616 commented
Las clases que te estoy pasando que no tienen que ver con la historia tienen errores de escritura, como Testiomonials, que hacian que no compile la solucion. Eso deberia pasarlo en un fix aparte ??

2022-09-04 12:30 UTC, emmanuelranone approved these changes

2022-09-04 12:30 UTC, merged